### ISSUE TITLE
Module path should be "github.com/mborders/artifex", not "github.com/borderstech/artifex"

### ISSUE THREAD

**Issue by KateGo520** [borderstech/artifex#3]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, as [doc](https://godoc.org/github.com/mborders/artifex) said, import "github.com/mborders/artifex", then get this error:

```
go: finding module for package github.com/mborders/artifex
go: downloading github.com/mborders/artifex v0.0.0-20191113201913-8ea03c710bd4
go: found github.com/mborders/artifex in github.com/mborders/artifex v0.0.0-20191113201913-8ea03c710bd4
go: test1 imports
        github.com/mborders/artifex: github.com/mborders/artifex@v0.0.0-20191113201913-8ea03c710bd4: parsing go.mod:
        module declares its path as: github.com/borderstech/artifex
                but was required as: github.com/mborders/artifex 
```

###  Fix the module path:
1) Rename the module path to "github.com/mborders/artifex": https://github.com/mborders/artifex/blob/master/go.mod#L1 
```
module github.com/mborders/artifex
require (
	…
) 
```
2) Change the [doc](https://godoc.org/github.com/mborders/artifex) document to use `import "github.com/borderstech/artifex"`.

**Comment by KateGo520** [comment]
@mborders @Prnyself  Could you help me review this issue? Thx :p

**Comment by mborders** [comment]
Sure thing, I will fix this!

**Comment by mborders** [comment]
Fixed!
