### ISSUE TITLE
Semver tag

### ISSUE THREAD

**Issue by pims** [borderstech/artifex#5]
Hi,

looks like a very useful module.
I tried to pull the latest version but it failed.

```
go get -v -u github.com/mborders/artifex@v0.4
go get github.com/mborders/artifex@v0.4: no matching versions for query "v0.4"
```

My understanding is that go.mod expects a semver tag and `v0.4` doesn't have the patch version. I would assume that tagging `v0.4.0` would work without having to change anything.

For now I can only get `v0.3.1` which incidentally follows semver.

**Comment by mborders** [comment]
Thank you for the feedback and pointing this out! I just updated the 0.4 release to be v0.4.0 and it should have that tag as well now too. Can you check if the following works now?
`go get github.com/mborders/artifex@v0.4.0`

I just tested and it's working now.

**Comment by pims** [comment]
Works now. Thanks!
